/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejemplomaxjni_lib_JavaDiscretas */

#ifndef _Included_ejemplomaxjni_lib_JavaDiscretas
#define _Included_ejemplomaxjni_lib_JavaDiscretas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ejemplomaxjni_lib_JavaDiscretas
 * Method:    calculardiscretas
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_ejemplomaxjni_lib_JavaDiscretas_calculardiscretas
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
